In [14]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [37]:
df = pd.read_csv("pet_adoption_data.csv")

In [38]:
df.describe()

,PetID,AgeMonths,WeightKg,Vaccinated,HealthCondition,TimeInShelterDays,AdoptionFee,PreviousOwner,AdoptionLikelihood
count,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000
mean,1503.000000,92.279522,15.705776,0.701046,0.196313,43.974091,249.142003,0.301943,0.328351
std,579.515315,52.148363,8.327749,0.457914,0.397307,25.740253,142.887040,0.459215,0.469730
min,500.000000,1.000000,1.018198,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,1001.500000,48.000000,8.730396,0.000000,0.000000,21.000000,127.000000,0.000000,0.000000
50%,1503.000000,94.000000,15.925416,1.000000,0.000000,45.000000,242.000000,0.000000,0.000000
75%,2004.500000,138.000000,22.737180,1.000000,0.000000,66.000000,375.000000,1.000000,1.000000
max,2506.000000,179.000000,29.995628,1.000000,1.000000,89.000000,499.000000,1.000000,1.000000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2007 entries, 0 to 2006
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   PetID               2007 non-null   int64
 1   PetType             2007 non-null   object
 2   Breed               2007 non-null   object
 3   AgeMonths           2007 non-null   int64
 4   Color               2007 non-null   object
 5   Size                2007 non-null   object
 6   WeightKg            2007 non-null   float64
 7   Vaccinated          2007 non-null   int64
 8   HealthCondition     2007 non-null   int64
 9   TimeInShelterDays   2007 non-null   int64
 10  AdoptionFee         2007 non-null   int64
 11  PreviousOwner       2007 non-null   int64
 12  AdoptionLikelihood  2007 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 204.0+ KB

In [42]:
X = df[['AgeMonths', 'WeightKg', 'Vaccinated', 'TimeInShelterDays', 'AdoptionFee', 'PreviousOwner']]

In [43]:
X.describe()

,AgeMonths,WeightKg,Vaccinated,TimeInShelterDays,AdoptionFee,PreviousOwner
count,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000,2007.000000
mean,92.279522,15.705776,0.701046,43.974091,249.142003,0.301943
std,52.148363,8.327749,0.457914,25.740253,142.887040,0.459215
min,1.000000,1.018198,0.000000,1.000000,0.000000,0.000000
25%,48.000000,8.730396,0.000000,21.000000,127.000000,0.000000
50%,94.000000,15.925416,1.000000,45.000000,242.000000,0.000000
75%,138.000000,22.737180,1.000000,66.000000,375.000000,1.000000
max,179.000000,29.995628,1.000000,89.000000,499.000000,1.000000

In [44]:
X.head()

,AgeMonths,WeightKg,Vaccinated,TimeInShelterDays,AdoptionFee,PreviousOwner
0,131,5.039768,1,27,140,0
1,73,16.086727,0,8,235,0
2,136,2.076286,0,85,385,0
3,97,3.339423,0,61,217,1
4,123,20.498100,0,28,14,1

In [45]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [46]:
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns
)

X_scaled.head()

,AgeMonths,WeightKg,Vaccinated,TimeInShelterDays,AdoptionFee,PreviousOwner
0,0.742691,-1.281098,0.653023,-0.659602,-0.764025,-0.657684
1,-0.369797,0.045756,-1.531339,-1.397929,-0.098998,-0.657684
2,0.838595,-1.637043,-1.531339,1.594240,0.951044,-0.657684
3,0.090543,-1.485328,-1.531339,0.661616,-0.225003,1.520487
4,0.589244,0.575608,-1.531339,-0.620743,-1.646060,1.520487

In [47]:
y = df['AdoptionLikelihood']

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [50]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [51]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)

In [52]:
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns)

In [53]:
import statsmodels.formula.api as smf

In [54]:
train_df = X_train_scaled.copy()
train_df['AdoptionLikelihood'] = y_train.values

In [55]:
train_df.head()

,AgeMonths,WeightKg,Vaccinated,TimeInShelterDays,AdoptionFee,PreviousOwner,AdoptionLikelihood
0,-0.461166,-0.063029,0.658054,1.156743,1.194905,-0.655139,1
1,1.541795,1.072712,-1.519631,-0.008836,1.118218,1.526393,0
2,1.484017,-0.569898,-1.519631,-0.047688,0.874212,-0.655139,0
3,0.829203,-1.541307,-1.519631,0.224280,0.658093,-0.655139,0
4,1.484017,1.369637,0.658054,1.117890,-1.342755,-0.655139,0

In [56]:
model = smf.ols(
    'AdoptionLikelihood ~ AgeMonths + WeightKg + Vaccinated + Vaccinated + TimeInShelterDays + AdoptionFee + PreviousOwner',
    data=train_df
).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:     AdoptionLikelihood   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.124
Method:                 Least Squares   F-statistic:                     38.69
Date:                Fri, 18 Sep 2026   Prob (F-statistic):           4.47e-44
Time:                        15:24:41   Log-Likelihood:                -955.40
No. Observations:                1605   AIC:                             1925.
Df Residuals:                    1598   BIC:                             1962.
Df Model:                           6
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             0.3283      0.011     29.912      0.000       0.307       0.350
AgeMonths            -0.0930      0.011     -8.456      0.000      -0.115      -0.071
WeightKg             -0.0011      0.011     -0.103      0.918      -0.023       0.020
Vaccinated            0.1397      0.011     12.717      0.000       0.118       0.161
TimeInShelterDays     0.0094      0.011      0.858      0.391      -0.012       0.031
AdoptionFee          -0.0042      0.011     -0.378      0.705      -0.026       0.017
PreviousOwner        -0.0058      0.011     -0.529      0.597      -0.027       0.016
==============================================================================
Omnibus:                     1458.800   Durbin-Watson:                   2.044
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              177.870
Skew:                           0.546   Prob(JB):                     2.38e-39
Kurtosis:                       1.789   Cond. No.                         1.09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.